version: '3'

volumes:
  db-data: 


services:
  web:
    build: .  #Build from DockerFile (not Docker-image)
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'    #Desginate the 相対パス
    environment:
      - 'DATABASE_PASSWORD=postgres'

    tty: true    #-t option (execute bash)
    stdin_open: true

    # docker-compose特有の概念
    depends_on: #service-containerができた後に、containerを作成する
      - db
    links:
      - db


  db:
    image: postgres
    volumes:   #dbのデータをhost-sideで保持しておきたい(他コンテナと共有する時とか)
      - 'db-data:/var/lib/postgres/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'

      # localhost以外の環境で、postgresを動かす場合に必要(travis.ci)
      - 'POSTGRES_HOST_AUTH_METHOD=trust'